# Dataset
dataset_train_path : '/home2/mint/UnityDataset/RealWorld/Unity/MovingCamera/Mocap/cont2_cvpr_finale_uniqE/train_set/'
dataset_val_path : '/home2/mint/UnityDataset/RealWorld/Unity/MovingCamera/Mocap/cont2_cvpr_finale_uniqE/val_set/'
trajectory_type: 'Mixed'
env: 'unity'

# Wandb
wandb_dir: '../'
wandb_notes: null
wandb_tags: 'CVPR_Week6_mocap_nodefC'
wandb_name: 'agg_bl_noeot_mocap_nodefC'

# Checkpoint
save_ckpt: '../model_checkpoints/'
load_ckpt: null # Lastest or Best

# Training parameters
batch_size: 512
n_epochs: 100000
lr: 0.001
clip: 1
decay_gamma: 0.7
decay_cycle: 1000
canonicalize: True
noise: True
annealing: False
annealing_cycle: 1
annealing_gamma:  0.7
augment: True
recon: 'clean'
optim_init_h: False

# Visualization
visualize: True
vis_path: '../../visualize_html/'

# Input variation
input_variation: 'intr_hori_vert' # 'intr_azim_elev'

# Model
pipeline:

  height:
    arch: 'lstm'
    bidirectional: True
    trainable_init: True
    rnn_hidden: 64
    rnn_stack: 2
    mlp_hidden: 32
    mlp_stack: 2
    in_node: 4
    out_node: 1
    extra_in: []
    extra_out: []
    latent_in: []
    latent_out: []
    i_s: 'dt'
    o_s: 'dt'
    constraint_y: null #'lrelu' # 'relu', 'softplus' or null
    attn: False
    noise_space: 'uv'
    noise_sd: 0.0
    agg: 'net_cat_h_agg'

# Features
selected_features: []
sc: ''  # ''(+0), azim(+1), elev(+1), both(+2)

# Loss
multiview_loss: []
loss_list: ['all']

# Miscellaneous
cuda_device_num: 0
w: 1664
h: 1088
fps: 60