# Dataset
#dataset_train_path: '../../Dataset/Single/train_set/'
#dataset_val_path: '../../Dataset/Single/val_set/'

dataset_train_path : '/home2/mint/UnityDataset/RealWorld/Unity/MovingCamera/Canonicalize/train_set/'
dataset_val_path : '/home2/mint/UnityDataset/RealWorld/Unity/MovingCamera/Canonicalize/val_set/'
trajectory_type: 'Mixed'
env: 'unity'

# Wandb
wandb_dir: './'
wandb_notes: null
wandb_tags: 'MovingCamera_CL'
wandb_name: 'dt_dt_cl'

# Checkpoint
save_ckpt: '../model_checkpoints/'
load_ckpt: null # Lastest or Best

# Training parameters
batch_size: 512
n_epochs: 100000
lr: 0.001
clip: 10
decay_gamma: 0.7
decay_cycle: 10000
canonicalize: True
noise: False
noise_sd: -1
annealing: False
annealing_cycle: 1000
annealing_gamma:  0.7

# Visualization
visualize: True
vis_path: '../../visualize_html/'

# Input variation
input_variation: 'intr_azim_elev' # 'intr_azim_elev'

# Model
pipeline:
  height:
    arch: 'lstm'
    bidirectional: True
    trainable_init: True
    rnn_hidden: 64
    rnn_stack: 2
    mlp_hidden: 32
    mlp_stack: 2
    in_node: 5
    out_node: 1
    extra_in: []
    extra_out: []
    latent_in: []
    latent_out: []
    i_s: 'dt_all'
    o_s: 'dt'
    constraint_y: null #'lrelu' # 'relu', 'softplus' or null
    attn: False
    noise_space: 'uv'
    noise_sd: 0.0

# Weighted Combining
si_pred_ramp: False

# Features
selected_features: []
sc: ''  # azim(+1), elev(+1), both(+2)

# Loss
multiview_loss: []

# Miscellaneous
cuda_device_num: 0
w: 1664
h: 1088
fps: 60