# Dataset
dataset_train_path : '/home/puntawat/Mint/Work/Vision/BallTrajectory_MovingCamera/Dataset/Simulation/Single_Ours_set/train_set/'
dataset_val_path : '/home/puntawat/Mint/Work/Vision/BallTrajectory_MovingCamera/Dataset/Simulation/Single_Ours_set/val_set/'
trajectory_type: 'Mixed'
env: 'unity'

# Wandb
wandb_dir: '../'
wandb_notes: null
wandb_tags: 'SOTA'
wandb_name: 'sota_cmp'

# Checkpoint
save_ckpt: '../model_checkpoints/'
load_ckpt: null # Lastest or Best

# Training parameters
batch_size: 100
n_epochs: 1400
lr: 0.001
clip: 1
decay_gamma: 0.7
decay_cycle: 10000
canonicalize: False
noise: True
annealing: False
annealing_cycle: 1
annealing_gamma:  0.7
augment: True
recon: 'clean'
optim_init_h: False

# Visualization
visualize: True
vis_path: '../../visualize_html/'

# Input variation
input_variation: 'intr_hori_vert'

# Model
pipeline:

  flag:
    arch: 'lstm'
    bidirectional: True
    trainable_init: True
    rnn_hidden: 64
    rnn_stack: 2
    mlp_hidden: 32
    mlp_stack: 2
    in_node: 4
    out_node: 1
    extra_in: []
    extra_out: []
    latent_in: []
    latent_out: []
    i_s: 'dt'
    o_s: 'dt'

  height:
    arch: 'lstm'
    bidirectional: True
    trainable_init: True
    rnn_hidden: 64
    rnn_stack: 2
    mlp_hidden: 32
    mlp_stack: 2
    in_node: 4
    out_node: 1
    extra_in: [1]
    extra_out: []
    latent_in: []
    latent_out: []
    i_s: 'dt'
    o_s: 'dt'
    agg: 'net_cat_h_agg'
    constraint_y: null #'lrelu' # 'relu', 'softplus' or null
    attn: False
    noise_space: 'uv'
    noise_sd: 0

  refinement:
    arch: 'lstm'
    bidirectional: True
    trainable_init: True
    rnn_hidden: 64
    rnn_stack: 2
    mlp_hidden: 32
    mlp_stack: 2
    in_node: 3
    out_node: 3
    extra_in: [4]
    extra_out: []
    latent_in: []
    latent_out: []
    i_s: 't'
    o_s: 't'
    attn: False
    refine: 'infref_xyz' # refinement space ('xyz', 'h')
    noise_space: null # adding noise space ('dh', 'h', 'xyz', 'dxyz', 'const_h')
    noise_sd: 0.0


# Features
selected_features: [eot]
sc: ''  # ''(+0), azim(+1), elev(+1), both(+2)

# Loss
multiview_loss: []
loss_list: ['all']

# Miscellaneous
cuda_device_num: 0
w: 1664
h: 1088
fps: 30
