# Dataset
#dataset_train_path: '../../Dataset/Single/train_set/'
#dataset_val_path: '../../Dataset/Single/val_set/'

dataset_train_path : '/home2/mint/UnityDataset/RealWorld/Unity/MovingCamera/TracknetV1/SimTennis/cont2_cd/train_set/'
dataset_val_path : '/home2/mint/UnityDataset/RealWorld/Unity/MovingCamera/TracknetV1_SimTennis/cont2_cd/val_set/'
trajectory_type: 'Mixed'
env: 'unity'

# Wandb
wandb_dir: './'
wandb_notes: null
wandb_tags: 'TracknetV1_SimTennis'
wandb_name: 'tennis_cont2_clean_cd_full'

# Checkpoint
save_ckpt: '../model_checkpoints/'
load_ckpt: null # Lastest or Best

# Training parameters
batch_size: 512
n_epochs: 100000
lr: 0.001
clip: 10
decay_gamma: 0.7
decay_cycle: 10000
canonicalize: False
noise: True
noise_sd: -1
annealing: False
annealing_cycle: 1000
annealing_gamma:  0.7
augment: null
recon: 'clean'

# Visualization
visualize: True
visualization_path: '../../visualize_html/'

# Model
pipeline:

  flag:
    arch: 'lstm'
    bidirectional: True
    trainable_init: True
    rnn_hidden: 64
    rnn_stack: 2
    mlp_hidden: 32
    mlp_stack: 2
    in_node: 5
    out_node: 1
    extra_in: []
    extra_out: []

  height:
    arch: 'lstm'
    bidirectional: True
    trainable_init: True
    rnn_hidden: 64
    rnn_stack: 2
    mlp_hidden: 32
    mlp_stack: 2
    in_node: 5
    out_node: 1
    extra_in: [1]
    extra_out: []

  refinement:
      arch: 'lstm'
      bidirectional: True
      trainable_init: True
      rnn_hidden: 64
      rnn_stack: 2
      mlp_hidden: 32
      mlp_stack: 2
      in_node: 3
      out_node: 3
      extra_in: []
      extra_out: []

# Features
selected_features: [cd]
i_s: 'dt'  # Input space
o_s: 'dt'  # Output space
sc: ''  # ''(+0), azim(+1), elev(+1), both(+2)

# Loss
multiview_loss: []

# Miscellaneous
cuda_device_num: 0