# Dataset
# dataset_train_path: '../../Dataset/Single/train_set/'
# dataset_val_path: '../../Dataset/Single/val_set/'
trajectory_type: 'Mixed'
env: 'unity'

# Wandb
wandb_dir: '/home/puntawat/Mint/Work/Vision/BallTrajectory_MovingCamera/'
wandb_notes: null
wandb_tags: 'MovingCamera_test'
wandb_name: 'test111'

# Checkpoint
save_ckpt: '../model_checkpoints/'
load_ckpt: null # Lastest or Best

# Training parameters
batch_size: 10
n_epochs: 100000
lr: 0.001
clip: 0
decay_gamma: 0.7
decay_cycle: 10000
canonicalize : False
noise: False 
noise_sd: -1
annealing: False
annealing_cycle: 1000
annealing_gamma:  0.7
augment: 'perc'

# Visualization
visualize: True
visualization_path: '/home/puntawat/Mint/Work/Vision/BallTrajectory_MovingCamera/visualize_html/'

# Model
pipeline:
  height:
    arch: 'lstm'
    bidirectional: True
    trainable_init: True
    rnn_hidden: 64
    rnn_stack: 2
    mlp_hidden: 32
    mlp_stack: 2
    in_node: 5
    out_node: 1
    extra_in: []
    extra_out: []


# Weighted Combining
si_pred_ramp: False

# Features
selected_features: []
i_s: 'dt'  # Input space
o_s: 'dt'  # Output space
sc: ''  # azim(+1), elev(+1), both(+2)

# Loss
multiview_loss: []

# Miscellaneous
cuda_device_num: 0
