# Dataset
dataset_train_path : '/home2/mint/UnityDataset/RealWorld/Mocap_rebuttal/train_set/'
dataset_val_path : '/home2/mint/UnityDataset/RealWorld/Mocap_rebuttal/val_set/'
# dataset_train_path : '/home/puntawat/Mint/Work/Vision/BallTrajectory_MovingCamera/Rebuttal/Mocap_rebuttal/train_set'
# dataset_val_path : '/home/puntawat/Mint/Work/Vision/BallTrajectory_MovingCamera/Rebuttal/Mocap_rebuttal/val_set'
trajectory_type: 'Mixed'
env: 'mocap'

# Wandb
wandb_dir: '../'
wandb_notes: null
wandb_tags: 'CVPR_Rebuttal'
wandb_name: 'mocap_finetuning_real'

# Checkpoint
save_ckpt: '../model_checkpoints/'
load_ckpt: null # Lastest or Best

# Training parameters
batch_size: 512
n_epochs: 100000
lr: 0.001
clip: 1
decay_gamma: 0.7
decay_cycle: 10000
canonicalize: True
noise: True
annealing: False
annealing_cycle: 1
annealing_gamma:  0.7
augment: True
recon: 'noisy'
optim_init_h: False

# Visualization
visualize: True
vis_path: '../../visualize_html/'

# Input variation
input_variation: 'intr_hori_vert' # 'intr_azim_elev'

# Model
pipeline:

  flag:
    arch: 'lstm'
    bidirectional: True
    trainable_init: True
    rnn_hidden: 64
    rnn_stack: 2
    mlp_hidden: 32
    mlp_stack: 2
    in_node: 4
    out_node: 1
    extra_in: []
    extra_out: []
    latent_in: []
    latent_out: []
    i_s: 'dt'
    o_s: 'dt'

  height:
    arch: 'lstm'
    bidirectional: True
    trainable_init: True
    rnn_hidden: 64
    rnn_stack: 2
    mlp_hidden: 32
    mlp_stack: 2
    in_node: 4
    out_node: 1
    extra_in: [1]
    extra_out: []
    latent_in: []
    latent_out: []
    i_s: 'dt'
    o_s: 'dt'
    constraint_y: null #'lrelu' # 'relu', 'softplus' or null
    attn: False
    noise_space: 'uv'
    noise_sd: '0t5'
    agg: 'net_cat_h_agg'

  refinement:
    arch: 'lstm'
    bidirectional: True
    trainable_init: True
    rnn_hidden: 64
    rnn_stack: 2
    mlp_hidden: 32
    mlp_stack: 2
    in_node: 3
    out_node: 3
    extra_in: [4]
    extra_out: []
    latent_in: []
    latent_out: []
    i_s: 't'
    o_s: 't'
    attn: False
    refine: 'infref_xyz' # refinement space ('xyz', 'h')
    noise_space: null # adding noise space ('dh', 'h', 'xyz')
    noise_sd: 0.0

# Features
selected_features: []
sc: ''  # ''(+0), azim(+1), elev(+1), both(+2)

# Loss
multiview_loss: []
loss_list: ['trajectory', 'bg']

# Miscellaneous
cuda_device_num: 0
w: 1664
h: 1088
fps: 60