# Dataset
#dataset_train_path: '../../Dataset/Single/train_set/'
#dataset_val_path: '../../Dataset/Single/val_set/'

dataset_train_path : '/home2/mint/UnityDataset/RealWorld/Unity/MovingCamera/Single/train_set/'
dataset_val_path : '/home2/mint/UnityDataset/RealWorld/Unity/MovingCamera/Single/val_set/'
trajectory_type: 'Mixed'
env: 'unity'

# Wandb
wandb_dir: './'
wandb_notes: null
wandb_tags: 'MovingCamera'
wandb_name: 'tdt_dt_sc'

# Checkpoint
save_ckpt: '../model_checkpoints/'
load_ckpt: null # Lastest or Best

# Training parameters
batch_size: 512
n_epochs: 100000
lr: 0.001
clip: 0
decay_gamma: 0.7
decay_cycle: 10000
noise: False
noise_sd: -1
annealing: False
annealing_cycle: 1000
annealing_gamma:  0.7

# Visualization
visualize: True
visualization_path: '../visualize_html/'

# Model
pipeline:
  height:
    arch: 'lstm'
    bidirectional: True
    trainable_init: True
    rnn_hidden: 64
    rnn_stack: 2
    mlp_hidden: 32
    mlp_stack: 2
    in_node: 5
    out_node: 1
    extra_in: [9]
    extra_out: []


# Weighted Combining
si_pred_ramp: False

# Features
selected_features: []
i_s: 't_dt'  # Input space
o_s: 'dt'  # Output space
sc: 'both'  # azim(+1), elev(+1), both(+2)

# Loss
multiview_loss: []

# Miscellaneous
cuda_device_num: 0